/**
 *  Object returned from https://ppubs.uspto.gov//dirsearch-public/patents/[patentGuid]/highlight
*/
export interface PPubsPatentHighlightAPIResponse {
  guid: string
  publicationReferenceDocumentNumber: string
  compositeId: string
  publicationReferenceDocumentNumber1: string
  datePublishedKwicHits: unknown
  datePublished: string
  inventionTitle: string
  type: string
  mainClassificationCode: string
  applicantName: unknown
  assigneeName: string[]
  uspcFullClassificationFlattened: string
  ipcCodeFlattened: string
  cpcInventiveFlattened: string
  cpcAdditionalFlattened: unknown
  applicationFilingDate: string[]
  applicationFilingDateKwicHits: unknown
  relatedApplFilingDate: string[]
  primaryExaminer: string
  assistantExaminer: unknown
  applicationNumber: string
  frontPageStart: number
  frontPageEnd: number
  drawingsStart: number
  drawingsEnd: number
  specificationStart: number
  specificationEnd: number
  claimsStart: number
  claimsEnd: number
  abstractStart: number
  abstractEnd: number
  bibStart: number
  bibEnd: number
  certCorrectionStart: number
  certCorrectionEnd: number
  certReexaminationStart: number
  certReexaminationEnd: number
  supplementalStart: number
  supplementalEnd: number
  ptabStart: number
  ptabEnd: number
  amendStart: number
  amendEnd: number
  searchReportStart: number
  searchReportEnd: number
  pageCount: number
  pageCountDisplay: string
  previouslyViewed: boolean
  unused: boolean
  imageLocation: string
  imageFileName: string
  cpcCodes: unknown
  queryId: number
  tags: unknown
  inventorsShort: string
  familyIdentifierCur: number
  familyIdentifierCurStr: string
  languageIndicator: string
  databaseName: string
  dwImageDoctypeList: unknown
  dwImageLocList: unknown
  dwPageCountList: unknown
  dwImageDocidList: unknown
  patentFamilyMembers: unknown
  patentFamilyCountry: unknown
  patentFamilySerialNumber: unknown
  documentIdWithDashesDw: unknown
  pfPublDate: unknown
  pfPublDateKwicHits: unknown
  priorityClaimsDate: string[]
  priorityClaimsDateKwicHits: unknown
  pfApplicationSerialNumber: unknown
  pfApplicationDescriptor: unknown
  pfLanguage: unknown
  pfApplicationDate: unknown
  pfApplicationDateKwicHits: unknown
  clippedUri: unknown
  source: unknown
  documentId: string
  derwentAccessionNumber: unknown
  documentSize: number
  score: number
  governmentInterest: unknown
  kindCode: string[]
  urpn: string[]
  urpnCode: string[]
  abstractedPatentNumber: unknown
  assigneeCity: string[]
  assigneePostalCode: string[]
  assigneeState: string[]
  assigneeTypeCode: string[]
  curIntlPatentClassificationPrimary: string[]
  curIntlPatentClassificationPrimaryDateKwicHits: unknown
  designatedStates: unknown
  examinerGroup: string
  issuedUsCrossRefClassification: string[]
  jpoFtermCurrent: unknown
  languageOfSpecification: unknown
  chosenDrawingsReference: unknown
  derwentClass: unknown
  inventionTitleHighlights: unknown
  cpcOrigInventiveClassificationHighlights: unknown
  cpcInventiveDateKwicHits: unknown
  cpcOrigAdditionalClassification: unknown
  cpcAdditionalDateKwicHits: unknown
  curIntlPatentClssficationSecHighlights: unknown
  fieldOfSearchClassSubclassHighlights: string[]
  cpcCombinationSetsCurHighlights: unknown
  applicantCountry: unknown
  applicantCity: unknown
  applicantState: unknown
  applicantZipCode: unknown
  applicantAuthorityType: unknown
  applicantDescriptiveText: unknown
  applicationSerialNumber: string[]
  inventorCity: string[]
  inventorState: string[]
  inventorPostalCode: string[]
  standardTitleTermsHighlights: unknown
  primaryExaminerHighlights: string
  continuityData: string[]
  inventors: unknown
  uspcFullClassification: unknown
  uspcCodeFmtFlattened: unknown
  ipcCode: unknown
  applicationNumberHighlights: string[]
  dateProduced: string
  auxFamilyMembersGroupTempPlaceHolder: unknown
  priorityCountryCode: unknown
  cpcCurAdditionalClassification: unknown
  internationalClassificationMain: unknown
  internationalClassificationSecondary: unknown
  internationalClassificationInformational: unknown
  europeanClassification: unknown
  europeanClassificationMain: unknown
  europeanClassificationSecondary: unknown
  lanuageIndicator: unknown
  intlPubClassificationPrimary: string[]
  intlPubClassificationPrimaryDateKwicHits: unknown
  intlPubClassificationSecondary: string[]
  intlPubClassificationSecondaryDateKwicHits: unknown
  publicationDate: unknown
  derwentWeekInt: number
  derwentWeek: unknown
  currentUsOriginalClassification: string
  currentUsCrossReferenceClassification: string[]
  locarnoClassification: unknown
  equivalentAbstractText: unknown
  hagueIntlRegistrationNumber: unknown
  hagueIntlFilingDate: unknown
  hagueIntlFilingDateKwicHits: unknown
  hagueIntlRegistrationDate: unknown
  hagueIntlRegistrationDateKwicHits: unknown
  hagueIntlRegistrationPubDate: unknown
  hagueIntlRegistrationPubDateKwicHits: unknown
  curIntlPatentClassificationNoninvention: unknown
  curIntlPatentClassificationNoninventionDateKwicHits: unknown
  curIntlPatentClassificationSecondary: string[]
  curIntlPatentClassificationSecondaryDateKwicHits: unknown
  abstractHtml: string
  descriptionHtml: string
  claimsHtml: string
  briefHtml: string
  backgroundTextHtml: string
  subHeadingM0Html: unknown
  subHeadingM1Html: unknown
  subHeadingM2Html: unknown
  subHeadingM3Html: unknown
  subHeadingM4Html: unknown
  subHeadingM5Html: unknown
  subHeadingM6Html: unknown
  usClassIssued: string
  issuedUsDigestRefClassifi: unknown
  datePublYear: string
  applicationYear: string
  pfDerwentWeekYear: unknown
  pfApplicationYear: unknown
  pfPublYear: unknown
  reissueApplNumber: unknown
  abstractHeader: unknown
  abstractedPublicationDerwent: unknown
  affidavit130BFlag: unknown
  affidavit130BText: unknown
  applicantGroup: unknown
  applicantHeader: unknown
  applicationFilingDateInt: number
  applicationFilingDateIntKwicHits: unknown
  applicationRefFilingType: unknown
  applicationReferenceGroup: unknown
  applicationSeriesAndNumber: string
  applicationSeriesCode: string
  assignee1: unknown
  assigneeDescriptiveText: string[]
  patentAssigneeTerms: unknown
  associateAttorneyName: unknown
  attorneyName: unknown
  biologicalDepositInformation: unknown
  applicationType: unknown
  unlinkedDerwentRegistryNumber: unknown
  unlinkedRingIndexNumbersRarerFragments: unknown
  claimStatement: string
  claimsTextAmended: unknown
  continuedProsecutionAppl: unknown
  cpcAdditionalLong: unknown
  cpcCisClassificationOrig: unknown
  cpcCombinationClassificationOrig: unknown
  cpcInventive: string[]
  cpcInventiveCurrentDateKwicHits: unknown
  cpcAdditional: unknown
  cpcAdditionalCurrentDateKwicHits: unknown
  cpcOrigClassificationGroup: unknown
  curIntlPatentClassificationGroup: unknown
  curUsClassificationUsPrimaryClass: unknown
  curUsClassificationUsSecondaryClass: unknown
  customerNumber: unknown
  depositAccessionNumber: unknown
  depositDescription: unknown
  derwentClassAlpha: unknown
  designatedstatesRouteGroup: unknown
  docAccessionNumber: unknown
  drawingDescription: unknown
  editionField: unknown
  exchangeWeek: unknown
  exemplaryClaimNumber: string[]
  familyIdentifierOrig: unknown
  fieldOfSearchCpcClassification: unknown
  fieldOfSearchCpcMainClass: unknown
  fieldOfSearchIpcMainClass: unknown
  fieldOfSearchIpcMainClassSubclass: unknown
  fieldOfSearchSubclasses: string[]
  foreignRefGroup: string[]
  foreignRefPubDate: string[]
  foreignRefPubDateKwicHits: string[]
  foreignRefCitationClassification: string[]
  foreignRefPatentNumber: string[]
  foreignRefCitationCpc: unknown
  foreignRefCountryCode: string[]
  iceXmlIndicator: string
  internationalClassificationHeader: unknown
  internationalClassificationInformationalGroup: unknown
  intlPubClassificationGroup: string[]
  intlPubClassificationNonInvention: unknown
  inventorCitizenship: unknown
  inventorCorrection: unknown
  inventorDeceased: unknown
  inventorStreetAddress: string[]
  inventorText: string[]
  jpoFiClassification: unknown
  legalRepresentativeCity: unknown
  legalRepresentativeCountry: string
  legalRepresentativeName: unknown
  legalRepresentativePostcode: unknown
  legalRepresentativeState: unknown
  legalRepresentativeStreetAddress: unknown
  legalRepresentativeText: unknown
  messengerDocsFlag: unknown
  newRecordPatentDerwent: unknown
  numberOfClaims: string
  numberOfDrawingSheets: string
  numberOfFigures: string
  numberOfPagesInSpecification: unknown
  numberOfPagesOfSpecification: unknown
  objectContents: unknown
  objectDescription: unknown
  parentDocCountry: unknown
  parentGrantDocCountry: unknown
  patentBibliographicHeader: unknown
  pctOrRegionalPublishingSerial: unknown
  pfDerwentWeekNum: unknown
  principalAttorneyName: unknown
  priorityApplicationCountry: unknown
  priorityClaimsCountry: string[]
  priorityNumberDerived: string[]
  publicationIssueNumber: unknown
  refCitedPatentDocNumber: unknown
  refCitedPatentDocDate: unknown
  refCitedPatentDocKindCode: unknown
  referenceCitedCode: unknown
  referenceCitedGroup: unknown
  referenceCitedSearchPhase: unknown
  referenceCitedText: unknown
  registrationNumber: unknown
  reissueApplCountry: unknown
  reissueParentKind: unknown
  reissueParentNumber: unknown
  reissueParentPubCountry: unknown
  reissuePatentGroup: unknown
  reissuePatentParentStatus: unknown
  reissuedPatentApplCountry: unknown
  reissuedPatentApplKind: unknown
  reissuedPatentApplNumber: unknown
  relatedApplChildPatentCountry: string[]
  relatedApplChildPatentName: unknown
  relatedApplChildPatentNumber: string[]
  relatedApplCountryCode: unknown
  relatedApplParentGrantPatentKind: unknown
  relatedApplParentGrantPatentName: unknown
  relatedApplParentPatentKind: unknown
  relatedApplParentPatentName: unknown
  relatedApplParentPctDoc: unknown
  relatedApplParentStatusCode: unknown
  relatedApplPatentNumber: string[]
  relatedApplRelatedPub: unknown
  relatedApplTypeOfCorrection: unknown
  rule47Flag: unknown
  selectedDrawingCharacter: unknown
  selectedDrawingFigure: unknown
  statutoryInventionText: unknown
  termOfExtension: string
  termOfPatentGrant: unknown
  titleTermsData: unknown
  additionalIndexingTerm: unknown
  applicationYearSearch: string
  pfApplicationYearSearch: unknown
  assigneeCountry: string[]
  certOfCorrectionFlag: unknown
  citedPatentLiteratureAddressInformation: unknown
  citedPatentLiteratureClassificationIpc: unknown
  citedPatentLiteratureOrganizationName: unknown
  citedPatentLiteratureRefNumber: unknown
  crossReferenceNumber: unknown
  country: string
  cpiManualCodes: unknown
  cpiSecondaryAccessionNumber: unknown
  curIntlPatentAllClassificationLong: unknown
  currentUsOriginalClassificationLong: unknown
  datePublSearch: string
  datePublYearSearch: string
  epiManualCodes: unknown
  fieldOfSearchMainClassNational: string[]
  inventorCountry: string[]
  ipcAllMainClassification: string[]
  issuedUsClassificationFull: string[]
  issuedUsDigestRefClassification: string[]
  jpoFiCurrentAdditionalClassification: unknown
  jpoFiCurrentInventiveClassification: unknown
  legalFirmName: string[]
  locarnoMainClassification: unknown
  nonCpiSecondaryAccessionNumber: unknown
  objectId: unknown
  otherRefPub: string[]
  pageNumber: unknown
  patentAssigneeCode: unknown
  patentAssigneeNameTotal: unknown
  patentFamilyDate: unknown
  patentFamilyDocNumber: unknown
  patentFamilyKind: unknown
  patentFamilyKindCode: unknown
  patentFamilyLanguage: unknown
  patentFamilyName: unknown
  patentNumberOfLocalApplication: unknown
  pct102eDate: unknown
  pct371c124Date: unknown
  pct371c124DateKwicHits: unknown
  pctFilingDate: unknown
  pctFilingDateKwicHits: unknown
  pctFilingDocCountryCode: unknown
  pctFilingKind: unknown
  pctFilingNumber: unknown
  pctName: unknown
  pctOrRegionalPublishingCountry: unknown
  pctOrRegionalPublishingKind: unknown
  pctOrRegionalPublishingName: unknown
  pctOrRegionalPublishingText: unknown
  pctPubDate: unknown
  pctPubDateKwicHits: unknown
  pctPubDocIdentifier: unknown
  pctPubNumber: unknown
  pfApplicationDateSearch: unknown
  pfApplicationType: unknown
  pfDerwentWeekDate: unknown
  pfPublDateSearch: unknown
  pfPublDateSearchKwicHits: unknown
  pfPublYearSearch: unknown
  polymerIndexingCodes: unknown
  polymerMultipunchCodeRecordNumber: unknown
  polymerMultipunchCodes: unknown
  priorPublishedDocCountryCode: string[]
  priorPublishedDocDate: string[]
  priorPublishedDocDateKwicHits: unknown
  priorPublishedDocIdentifier: string[]
  priorPublishedDocKindCode: string[]
  priorPublishedDocNumber: string[]
  priorityApplYear: string[]
  priorityApplicationDate: unknown
  priorityClaimsDateSearch: unknown
  priorityClaimsDocNumber: string[]
  priorityPatentDid: unknown
  priorityPatentNumber: unknown
  ptabCertFlag: unknown
  pubRefCountryCode: unknown
  pubRefDocNumber: string
  pubRefDocNumber1: string
  publicationData: unknown
  recordPatentNumber: unknown
  reexaminationFlag: unknown
  refCitedOthers: unknown
  refCitedPatentDocCountryCode: unknown
  refCitedPatentDocName: unknown
  refCitedPatentRelevantPassage: unknown
  reissueParentIssueDate: unknown
  reissuedPatentApplFilingDate: unknown
  relatedAccessionNumbers: unknown
  relatedApplChildPatentDate: unknown
  relatedApplFilingDateKwicHits: unknown
  relatedApplNumber: string[]
  relatedApplPatentIssueDate: unknown
  relatedApplPatentIssueDateKwicHits: unknown
  relatedDocumentKindCode: unknown
  securityLegend: unknown
  sequenceCwu: unknown
  sequenceListNewRules: unknown
  sequenceListOldRules: unknown
  sequencesListText: unknown
  standardTitleTerms: unknown
  supplementalExaminationFlag: unknown
  usBotanicLatinName: unknown
  usBotanicVariety: unknown
  usRefClassification: string[]
  usRefCpcClassification: unknown
  usRefGroup: string[]
  usRefIssueDate: string[]
  usRefIssueDateKwicHits: string[]
  usRefPatenteeName: string[]
  volumeNumber: unknown
  correspondenceNameAddress: unknown
  correspondenceAddressCustomerNumber: unknown
  ibmtdbAccessionNumber: unknown
  inventorsName: string[]
  applicationKindCode: string
  inventorNameDerived: unknown
  intlPubClassificationClass: string[]
  issuedUsOrigClassification: string
  curCpcSubclassFull: string[]
  cpcCurAdditionalClass: unknown
  cpcCurInventiveClass: string[]
  cpcCurClassificationGroup: string[]
  curCpcClassificationFull: string[]
  cpcCombinationClassificationCur: unknown
  cpcCombinationTallyCur: unknown
  intlFurtherClassification: unknown
  currentUsPatentClass: string[]
  curIntlPatentClassifictionPrimaryDateKwicHits: unknown
  curIntlPatentClssifSecHlights: unknown
  internationalClassificationInfom: unknown
  cpcOrigInventvClssifHlghts: unknown
  idWithoutSolrPartition: string
  descriptionStart: number
  descriptionEnd: number
  publicationReferenceDocumentNumberOne: string
}
